    ax1.plot(cumulative_pnl.index, cumulative_pnl.values, linewidth=2, color='green')
    ax1.set_title('Cumulative P&L', fontsize=14, fontweight='bold')
    ax1.set_xlabel('Trade Number')
    ax1.set_ylabel('Cumulative P&L ($)')
    ax1.grid(True, alpha=0.3)
    ax1.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, p: f'${x:,.0f}'))
    
    # 2. Trade P&L Distribution
    ax2 = plt.subplot(3, 3, 2)
    ax2.hist(trades_df['net_pnl'], bins=50, alpha=0.7, color='steelblue', edgecolor='black')
    ax2.axvline(trades_df['net_pnl'].mean(), color='red', linestyle='--', 
               label=f'Mean: ${trades_df[\"net_pnl\"].mean():.2f}')
    ax2.set_title('Trade P&L Distribution', fontsize=14, fontweight='bold')
    ax2.set_xlabel('Net P&L ($)')
    ax2.set_ylabel('Frequency')
    ax2.legend()
    ax2.grid(True, alpha=0.3)
    
    # 3. Daily P&L
    ax3 = plt.subplot(3, 3, 3)
    colors = ['green' if x > 0 else 'red' for x in daily_pnl.values]
    ax3.bar(range(len(daily_pnl)), daily_pnl.values, color=colors, alpha=0.7)
    ax3.set_title('Daily P&L', fontsize=14, fontweight='bold')
    ax3.set_xlabel('Trading Day')
    ax3.set_ylabel('Daily P&L ($)')
    ax3.grid(True, alpha=0.3)
    
    # 4. Exit Reason Analysis
    ax4 = plt.subplot(3, 3, 4)
    exit_counts = trades_df['exit_reason'].value_counts()
    ax4.pie(exit_counts.values, labels=exit_counts.index, autopct='%1.1f%%', startangle=90)
    ax4.set_title('Trade Exit Reasons', fontsize=14, fontweight='bold')
    
    # 5. Win/Loss by Position Type
    ax5 = plt.subplot(3, 3, 5)
    position_performance = trades_df.groupby(['type', trades_df['net_pnl'] > 0]).size().unstack()
    position_performance.columns = ['Losses', 'Wins']
    position_performance.plot(kind='bar', ax=ax5, color=['red', 'green'], alpha=0.7)
    ax5.set_title('Win/Loss by Position Type', fontsize=14, fontweight='bold')
    ax5.set_xlabel('Position Type')
    ax5.set_ylabel('Number of Trades')
    ax5.legend()
    ax5.grid(True, alpha=0.3)
    plt.setp(ax5.xaxis.get_majorticklabels(), rotation=0)
    
    plt.tight_layout()
    plt.show()
    
    # Performance Statistics
    print("\\n" + "="*80)
    print("📊 DETAILED PERFORMANCE STATISTICS")
    print("="*80)
    
    print("\\n📈 TRADE STATISTICS:")
    print(f"Total Trades: {summary['total_trades']:,}")
    print(f"Long/Short: {summary['long_trades']:,}/{summary['short_trades']:,}")
    print(f"Win Rate: {summary['win_rate']:.2f}%")
    print(f"Winning/Losing Trades: {summary['winning_trades']:,}/{summary['losing_trades']:,}")
    print(f"Average Winning Trade: ${summary['avg_winning_trade']:.2f}")
    print(f"Average Losing Trade: ${summary['avg_losing_trade']:.2f}")
    print(f"Profit Factor: {summary['profit_factor']:.2f}")
    
    print("\\n💰 P&L STATISTICS:")
    print(f"Total Net P&L: ${summary['total_pnl']:,.2f}")
    print(f"Gross P&L: ${summary['gross_pnl']:,.2f}")
    print(f"Transaction Costs: ${summary['total_transaction_costs']:,.2f}")
    print(f"Average P&L per Trade: ${summary['avg_pnl_per_trade']:.2f}")
    print(f"Max Drawdown: ${summary['max_drawdown']:,.2f}")
    
    print("\\n📅 DAILY STATISTICS:")
    print(f"Trading Days: {summary['total_trading_days']}")
    print(f"Profitable/Loss Days: {summary['profitable_days']}/{summary['losing_days']}")
    print(f"Daily Win Rate: {summary['daily_win_rate']:.1f}%")
    print(f"Average Daily P&L: ${summary['avg_daily_pnl']:,.2f}")
    print(f"Best/Worst Day: ${summary['max_daily_gain']:,.2f}/${summary['max_daily_loss']:,.2f}")
    print(f"Sharpe Ratio: {summary['sharpe_ratio']:.3f}")
    
    # Statistical Significance
    print("\\n📈 STATISTICAL ANALYSIS:")
    t_stat, p_value = stats.ttest_1samp(trades_df['net_pnl'], 0)
    print(f"T-Statistic: {t_stat:.3f}")
    print(f"P-Value: {p_value:.6f}")
    if p_value < 0.05:
        print("✅ Strategy is statistically significant (p < 0.05)")
    else:
        print("⚠️ Strategy is not statistically significant (p ≥ 0.05)")

# Generate the comprehensive report
if 'results' in locals() and results:
    generate_performance_report(results)
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "parameter-optimization",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Parameter Optimization Analysis\n",
    "def optimize_parameters(daily_data, param_ranges):\n",
    "    print(\"\\n🔧 PARAMETER OPTIMIZATION ANALYSIS\")\n",
    "    print(\"=\"*60)\n",
    "    \n",
    "    optimization_results = []\n",
    "    total_combinations = len(param_ranges['entry_bps']) * len(param_ranges['stop_loss_bps']) * len(param_ranges['profit_target_bps'])\n",
    "    current_test = 0\n",
    "    \n",
    "    for entry_bps in param_ranges['entry_bps']:\n",
    "        for stop_loss_bps in param_ranges['stop_loss_bps']:\n",
    "            for profit_target_bps in param_ranges['profit_target_bps']:\n",
    "                current_test += 1\n",
    "                print(f\"\\rTesting {current_test}/{total_combinations}: Entry={entry_bps}, Stop={stop_loss_bps}, Target={profit_target_bps}\", end=\"\")\n",
    "                \n",
    "                test_strategy = SP500IntradayMomentumStrategy(\n",
    "                    entry_bps=entry_bps,\n",
    "                    stop_loss_bps=stop_loss_bps,\n",
    "                    profit_target_bps=profit_target_bps,\n",
    "                    transaction_cost=TRANSACTION_COST,\n",
    "                    tick_value=TICK_VALUE\n",
    "                )\n",
    "                \n",
    "                test_results = test_strategy.backtest(daily_data)\n",
    "                \n",
    "                if test_results and test_results['summary']['total_trades'] > 0:\n",
    "                    summary = test_results['summary']\n",
    "                    optimization_results.append({\n",
    "                        'entry_bps': entry_bps,\n",
    "                        'stop_loss_bps': stop_loss_bps,\n",
    "                        'profit_target_bps': profit_target_bps,\n",
    "                        'total_pnl': summary['total_pnl'],\n",
    "                        'total_trades': summary['total_trades'],\n",
    "                        'win_rate': summary['win_rate'],\n",
    "                        'sharpe_ratio': summary['sharpe_ratio'],\n",
    "                        'avg_pnl_per_trade': summary['avg_pnl_per_trade']\n",
    "                    })\n",
    "    \n",
    "    print(\"\\n\")\n",
    "    \n",
    "    if not optimization_results:\n",
    "        print(\"❌ No valid parameter combinations found.\")\n",
    "        return None\n",
    "    \n",
    "    opt_df = pd.DataFrame(optimization_results)\n",
    "    opt_df = opt_df.sort_values('total_pnl', ascending=False)\n",
    "    \n",
    "    print(f\"✅ Tested {len(optimization_results)} parameter combinations\")\n",
    "    print(\"\\n🏆 TOP 10 PARAMETER COMBINATIONS:\")\n",
    "    print(opt_df.head(10).to_string(index=False))\n",
    "    \n",
    "    best_params = opt_df.iloc[0]\n",
    "    print(f\"\\n🎯 OPTIMAL PARAMETERS:\")\n",
    "    print(f\"Entry: {best_params['entry_bps']} bps, Stop: {best_params['stop_loss_bps']} bps, Target: {best_params['profit_target_bps']} bps\")\n",
    "    print(f\"Expected P&L: ${best_params['total_pnl']:,.2f}, Win Rate: {best_params['win_rate']:.1f}%\")\n",
    "    \n",
    "    return opt_df\n",
    "\n",
    "# Define parameter ranges\n",
    "param_ranges = {\n",
    "    'entry_bps': [1.0, 1.5, 2.0, 2.5, 3.0],\n",
    "    'stop_loss_bps': [0.5, 0.75, 1.0, 1.25],\n",
    "    'profit_target_bps': [1.5, 2.0, 2.5, 3.0]\n",
    "}\n",
    "\n",
    "print(\"\\n⚡ Ready to run parameter optimization...\")\n",
    "print(\"Uncomment the line below to run optimization:\")\n",
    "print(\"# optimization_results = optimize_parameters(combined_data, param_ranges)\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "export-results",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Export Results\n",
    "def export_results(results, filename_prefix=\"sp500_strategy\"):\n",
    "    if not results:\n",
    "        print(\"No results to export\")\n",
    "        return\n",
    "    \n",
    "    from datetime import datetime\n",
    "    timestamp = datetime.now().strftime(\"%Y%m%d_%H%M%S\")\n",
    "    \n",
    "    # Export trades to CSV\n",
    "    trades_filename = f\"{filename_prefix}_trades_{timestamp}.csv\"\n",
    "    results['trades_df'].to_csv(trades_filename, index=False)\n",
    "    print(f\"✅ Exported trades to: {trades_filename}\")\n",
    "    \n",
    "    # Export daily P&L\n",
    "    daily_filename = f\"{filename_prefix}_daily_pnl_{timestamp}.csv\"\n",
    "    daily_df = pd.DataFrame({\n",
    "        'date': results['daily_pnl'].index,\n",
    "        'daily_pnl': results['daily_pnl'].values\n",
    "    })\n",
    "    daily_df.to_csv(daily_filename, index=False)\n",
    "    print(f\"✅ Exported daily P&L to: {daily_filename}\")\n",
    "    \n",
    "    # Export summary\n",
    "    summary_filename = f\"{filename_prefix}_summary_{timestamp}.txt\"\n",
    "    with open(summary_filename, 'w') as f:\n",
    "        summary = results['summary']\n",
    "        f.write(\"S&P 500 INTRADAY MOMENTUM STRATEGY - PERFORMANCE SUMMARY\\n\")\n",
    "        f.write(\"=\" * 60 + \"\\n\\n\")\n",
    "        f.write(f\"Total Trades: {summary['total_trades']:,}\\n\")\n",
    "        f.write(f\"Win Rate: {summary['win_rate']:.2f}%\\n\")\n",
    "        f.write(f\"Total Net P&L: ${summary['total_pnl']:,.2f}\\n\")\n",
    "        f.write(f\"Gross P&L: ${summary['gross_pnl']:,.2f}\\n\")\n",
    "        f.write(f\"Transaction Costs: ${summary['total_transaction_costs']:,.2f}\\n\")\n",
    "        f.write(f\"Sharpe Ratio: {summary['sharpe_ratio']:.3f}\\n\")\n",
    "        f.write(f\"Max Drawdown: ${summary['max_drawdown']:,.2f}\\n\")\n",
    "        \n",
    "    print(f\"✅ Exported summary to: {summary_filename}\")\n",
    "    \n",
    "    return {\n",
    "        'trades_file': trades_filename,\n",
    "        'daily_file': daily_filename,\n",
    "        'summary_file': summary_filename\n",
    "    }\n",
    "\n",
    "# Export results if available\n",
    "if 'results' in locals() and results:\n",
    "    print(\"\\n📁 EXPORTING RESULTS...\")\n",
    "    exported_files = export_results(results)\n",
    "    print(\"\\n✅ All results exported successfully!\")\nelse:\n",
    "    print(\"❌ No results available for export. Run the strategy first.\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "usage-instructions",
   "metadata": {},
   "source": [
    "## 📋 Usage Instructions\n",
    "\n",
    "### Basic Usage:\n",
    "1. **Configure Parameters**: Modify strategy parameters in the configuration cell\n",
    "2. **Load Data**: Run the data loading cell to fetch S&P 500 data\n",
    "3. **Execute Strategy**: Run the strategy execution cell to perform backtest\n",
    "4. **Generate Reports**: Run the performance reporting cell for analysis\n",
    "\n",
    "### Advanced Analysis:\n",
    "- **Parameter Optimization**: Uncomment optimization code to find optimal parameters\n",
    "- **Export Results**: Export all results to CSV files for external analysis\n",
    "\n",
    "### Customization Options:\n",
    "- **Time Periods**: Change `start_date` and `end_date` to test different periods\n",
    "- **Strategy Parameters**: Adjust entry thresholds, stop losses, and profit targets\n",
    "- **Transaction Costs**: Modify transaction costs to reflect your broker's fees\n",
    "\n",
    "### Performance Metrics:\n",
    "- **Trade Statistics**: Win rate, profit factor, average P&L per trade\n",
    "- **Risk Metrics**: Sharpe ratio, maximum drawdown\n",
    "- **Statistical Tests**: T-tests for significance\n",
    "- **Visualizations**: P&L curves, distribution analysis\n",
    "\n",
    "### Notes:\n",
    "- Strategy simulates 5-minute intraday data from daily OHLC\n",
    "- All trades are closed by market close (no overnight positions)\n",
    "- Transaction costs are applied to every trade\n",
    "- Results include comprehensive statistical analysis"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python (OpenBB)",
   "language": "python",
   "name": "alfa-class-env"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "header",
   "metadata": {},
   "source": [
    "# S&P 500 Intraday Momentum Trading Strategy\n",
    "## Comprehensive Backtest and Analysis Notebook\n",
    "\n",
    "This notebook implements and analyzes the S&P 500 intraday momentum strategy with:\n",
    "- Complete strategy implementation\n",
    "- Performance analytics and visualization\n",
    "- Parameter optimization\n",
    "- Risk analysis and stress testing\n",
    "- Comprehensive reporting"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "imports",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "from datetime import datetime, timedelta\n",
    "from scipy import stats\n",
    "import warnings\n",
    "from openbb import obb\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "# Set style for better plots\n",
    "plt.style.use('seaborn-v0_8')\n",
    "sns.set_palette(\"husl\")\n",
    "print(\"✅ All libraries imported successfully!\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "configuration",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Configuration - Modify these parameters for testing\n",
    "symbols = ['^SPX']\n",
    "start_date = '2024-01-01'\n",
    "end_date = None  # None for current date, or specify like '2024-06-30'\n",
    "initial_capital = 10000\n",
    "\n",
    "# Strategy Parameters - Modify these for optimization\n",
    "ENTRY_THRESHOLD_BPS = 2      # Entry signal threshold in basis points\n",
    "STOP_LOSS_BPS = 0.75         # Stop loss in basis points\n",
    "PROFIT_TARGET_BPS = 2        # Profit target in basis points\n",
    "TRANSACTION_COST = 0.445     # Transaction cost per trade\n",
    "TICK_VALUE = 100             # Dollar value per tick\n",
    "\n",
    "print(f\"Strategy Configuration:\")\n",
    "print(f\"Entry Threshold: {ENTRY_THRESHOLD_BPS} bps\")\n",
    "print(f\"Stop Loss: {STOP_LOSS_BPS} bps\")\n",
    "print(f\"Profit Target: {PROFIT_TARGET_BPS} bps\")\n",
    "print(f\"Transaction Cost: ${TRANSACTION_COST}\")\n",
    "print(f\"Analysis Period: {start_date} to {end_date or 'current'}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "data-loading",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Fetch S&P 500 data\n",
    "dataframes = []\n",
    "\n",
    "for symbol in symbols:\n",
    "    try:\n",
    "        data_params = {\n",
    "            \"symbol\": symbol,\n",
    "            \"start_date\": start_date,\n",
    "            \"provider\": \"yfinance\"\n",
    "        }\n",
    "        \n",
    "        if end_date:\n",
    "            data_params[\"end_date\"] = end_date\n",
    "            \n",
    "        data = obb.equity.price.historical(**data_params).to_df()\n",
    "        data['Symbol'] = symbol\n",
    "        dataframes.append(data)\n",
    "        print(f\"✅ Successfully loaded data for {symbol}\")\n",
    "    except Exception as e:\n",
    "        print(f\"❌ Failed to fetch data for {symbol}: {str(e)}\")\n",
    "\n",
    "if dataframes:\n",
    "    combined_data = pd.concat(dataframes)\n",
    "    combined_data = combined_data.reset_index()\n",
    "    \n",
    "    print(f\"\\n📊 Data Summary:\")\n",
    "    print(f\"Total records: {len(combined_data)}\")\n",
    "    print(f\"Date range: {combined_data['date'].min()} to {combined_data['date'].max()}\")\n",
    "    print(f\"Price range: ${combined_data['low'].min():.2f} - ${combined_data['high'].max():.2f}\")\n",
    "    \n",
    "    # Display first few rows\n",
    "    display(combined_data.head())\n",
    "else:\n",
    "    print(\"❌ No data loaded. Check your configuration.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "strategy-class",
   "metadata": {},
   "outputs": [],
   "source": [
    "class SP500IntradayMomentumStrategy:\n",
    "    \"\"\"\n",
    "    S&P 500 Intraday Momentum Trading Strategy\n",
    "    \n",
    "    Strategy Logic:\n",
    "    1. Use previous day close as baseline\n",
    "    2. Enter LONG when price moves +X bps from baseline\n",
    "    3. Enter SHORT when price moves -X bps from baseline\n",
    "    4. Exit on stop loss or profit target\n",
    "    5. Force close all positions at market close\n",
    "    6. No overnight positions\n",
    "    \"\"\"\n",
    "    \n",
    "    def __init__(self, entry_bps=2, stop_loss_bps=0.75, profit_target_bps=2, \n",
    "                 transaction_cost=0.445, tick_value=100):\n",
    "        self.entry_bps = entry_bps\n",
    "        self.stop_loss_bps = stop_loss_bps\n",
    "        self.profit_target_bps = profit_target_bps\n",
    "        self.transaction_cost = transaction_cost\n",
    "        self.tick_value = tick_value\n",
    "        \n",
    "        # Results storage\n",
    "        self.trades = []\n",
    "        self.daily_pnl = {}\n",
    "        \n",
    "    def bps_to_percentage(self, bps):\n",
    "        \"\"\"Convert basis points to decimal percentage\"\"\"\n",
    "        return bps / 10000\n",
    "    \n",
    "    def simulate_intraday_data(self, daily_data, num_periods=78):\n",
    "        \"\"\"Simulate 5-minute intraday data from daily OHLC\"\"\"\n",
    "        intraday_data = []\n",
    "        \n",
    "        for _, day in daily_data.iterrows():\n",
    "            date_str = day['date'].strftime('%Y-%m-%d')\n",
    "            open_price = day['open']\n",
    "            high_price = day['high']\n",
    "            low_price = day['low']\n",
    "            close_price = day['close']\n",
    "            \n",
    "            # Create realistic price path\n",
    "            price_range = high_price - low_price\n",
    "            volatility = price_range / open_price\n",
    "            returns = np.random.normal(0, volatility/10, num_periods)\n",
    "            cumulative_returns = np.cumsum(returns)\n",
    "            cumulative_returns = cumulative_returns - cumulative_returns[0]\n",
    "            \n",
    "            if np.max(cumulative_returns) - np.min(cumulative_returns) > 0:\n",
    "                scale_factor = (price_range * 0.8) / (np.max(cumulative_returns) - np.min(cumulative_returns))\n",
    "                cumulative_returns *= scale_factor\n",
    "            \n",
    "            prices = open_price + cumulative_returns\n",
    "            high_idx = np.random.randint(10, num_periods-10)\n",
    "            low_idx = np.random.randint(10, num_periods-10)\n",
    "            prices[high_idx] = high_price\n",
    "            prices[low_idx] = low_price\n",
    "            prices[-1] = close_price\n",
    "            \n",
    "            # Generate intraday OHLC bars\n",
    "            for i in range(num_periods):\n",
    "                timestamp = pd.Timestamp(f\"{date_str} 09:30:00\") + pd.Timedelta(minutes=5*i)\n",
    "                bar_open = open_price if i == 0 else prices[i-1]\n",
    "                bar_close = prices[i]\n",
    "                bar_range = abs(bar_close - bar_open) * 1.5 + 0.5\n",
    "                bar_high = max(bar_open, bar_close) + np.random.uniform(0, bar_range/2)\n",
    "                bar_low = min(bar_open, bar_close) - np.random.uniform(0, bar_range/2)\n",
    "                \n",
    "                intraday_data.append({\n",
    "                    'timestamp': timestamp,\n",
    "                    'date': day['date'],\n",
    "                    'open': round(bar_open, 2),\n",
    "                    'high': round(bar_high, 2),\n",
    "                    'low': round(bar_low, 2),\n",
    "                    'close': round(bar_close, 2)\n",
    "                })\n",
    "        \n",
    "        return pd.DataFrame(intraday_data)\n",
    "    \n",
    "    def backtest(self, daily_data):\n",
    "        \"\"\"Run the complete backtest on daily data\"\"\"\n",
    "        print(\"🔄 Generating intraday data simulation...\")\n",
    "        intraday_data = self.simulate_intraday_data(daily_data)\n",
    "        print(f\"🚀 Backtesting strategy on {len(intraday_data)} intraday periods...\")\n",
    "        \n",
    "        trading_days = intraday_data.groupby('date')\n",
    "        previous_close = None\n",
    "        \n",
    "        for date, day_data in trading_days:\n",
    "            if previous_close is None:\n",
    "                previous_close = day_data.iloc[-1]['close']\n",
    "                continue\n",
    "            \n",
    "            day_trades = self.trade_single_day(day_data, previous_close, date)\n",
    "            self.trades.extend(day_trades)\n",
    "            daily_pnl = sum([trade['net_pnl'] for trade in day_trades])\n",
    "            self.daily_pnl[date] = daily_pnl\n",
    "            previous_close = day_data.iloc[-1]['close']\n",
    "        \n",
    "        print(f\"✅ Backtest completed! Generated {len(self.trades)} trades over {len(self.daily_pnl)} days\")\n",
    "        return self.get_results()\n",
    "    \n",
    "    def trade_single_day(self, day_data, baseline_price, date):\n",
    "        \"\"\"Execute trades for a single trading day\"\"\"\n",
    "        trades = []\n",
    "        baseline = baseline_price\n",
    "        current_position = None\n",
    "        entry_price = 0\n",
    "        entry_time = None\n",
    "        \n",
    "        day_data = day_data.sort_values('timestamp').reset_index(drop=True)\n",
    "        \n",
    "        for idx, candle in day_data.iterrows():\n",
    "            current_time = candle['timestamp']\n",
    "            hour = current_time.hour\n",
    "            can_enter_new_position = hour < 15\n",
    "            must_close_position = hour >= 16\n",
    "            \n",
    "            if current_position is None and can_enter_new_position:\n",
    "                up_threshold = baseline * (1 + self.bps_to_percentage(self.entry_bps))\n",
    "                down_threshold = baseline * (1 - self.bps_to_percentage(self.entry_bps))\n",
    "                \n",
    "                if candle['high'] >= up_threshold:\n",
    "                    current_position = 'LONG'\n",
    "                    entry_price = up_threshold\n",
    "                    entry_time = current_time\n",
    "                elif candle['low'] <= down_threshold:\n",
    "                    current_position = 'SHORT'\n",
    "                    entry_price = down_threshold\n",
    "                    entry_time = current_time\n",
    "            \n",
    "            elif current_position is not None:\n",
    "                exit_price = None\n",
    "                exit_reason = ''\n",
    "                \n",
    "                if must_close_position:\n",
    "                    exit_price = candle['close']\n",
    "                    exit_reason = 'Market Close'\n",
    "                elif current_position == 'LONG':\n",
    "                    stop_loss = baseline * (1 - self.bps_to_percentage(self.stop_loss_bps))\n",
    "                    profit_target = entry_price * (1 + self.bps_to_percentage(self.profit_target_bps))\n",
    "                    \n",
    "                    if candle['low'] <= stop_loss:\n",
    "                        exit_price = stop_loss\n",
    "                        exit_reason = 'Stop Loss'\n",
    "                    elif candle['high'] >= profit_target:\n",
    "                        exit_price = profit_target\n",
    "                        exit_reason = 'Profit Target'\n",
    "                \n",
    "                elif current_position == 'SHORT':\n",
    "                    stop_loss = baseline * (1 + self.bps_to_percentage(self.stop_loss_bps))\n",
    "                    profit_target = entry_price * (1 - self.bps_to_percentage(self.profit_target_bps))\n",
    "                    \n",
    "                    if candle['high'] >= stop_loss:\n",
    "                        exit_price = stop_loss\n",
    "                        exit_reason = 'Stop Loss'\n",
    "                    elif candle['low'] <= profit_target:\n",
    "                        exit_price = profit_target\n",
    "                        exit_reason = 'Profit Target'\n",
    "                \n",
    "                if exit_price is not None:\n",
    "                    if current_position == 'LONG':\n",
    "                        gross_pnl = (exit_price - entry_price) * self.tick_value\n",
    "                    else:\n",
    "                        gross_pnl = (entry_price - exit_price) * self.tick_value\n",
    "                    \n",
    "                    net_pnl = gross_pnl - self.transaction_cost\n",
    "                    \n",
    "                    trades.append({\n",
    "                        'date': date,\n",
    "                        'type': current_position,\n",
    "                        'entry_time': entry_time,\n",
    "                        'exit_time': current_time,\n",
    "                        'entry_price': entry_price,\n",
    "                        'exit_price': exit_price,\n",
    "                        'gross_pnl': gross_pnl,\n",
    "                        'transaction_cost': self.transaction_cost,\n",
    "                        'net_pnl': net_pnl,\n",
    "                        'exit_reason': exit_reason\n",
    "                    })\n",
    "                    \n",
    "                    baseline = exit_price\n",
    "                    current_position = None\n",
    "                    entry_price = 0\n",
    "                    entry_time = None\n",
    "        \n",
    "        return trades\n",
    "    \n",
    "    def get_results(self):\n",
    "        \"\"\"Calculate and return comprehensive performance metrics\"\"\"\n",
    "        if not self.trades:\n",
    "            return {}\n",
    "        \n",
    "        trades_df = pd.DataFrame(self.trades)\n",
    "        total_trades = len(trades_df)\n",
    "        winning_trades = len(trades_df[trades_df['net_pnl'] > 0])\n",
    "        losing_trades = len(trades_df[trades_df['net_pnl'] < 0])\n",
    "        \n",
    "        total_pnl = trades_df['net_pnl'].sum()\n",
    "        total_transaction_costs = trades_df['transaction_cost'].sum()\n",
    "        gross_pnl = trades_df['gross_pnl'].sum()\n",
    "        win_rate = (winning_trades / total_trades) * 100 if total_trades > 0 else 0\n",
    "        \n",
    "        daily_pnl_series = pd.Series(self.daily_pnl)\n",
    "        profitable_days = len(daily_pnl_series[daily_pnl_series > 0])\n",
    "        losing_days = len(daily_pnl_series[daily_pnl_series < 0])\n",
    "        \n",
    "        avg_win = trades_df[trades_df['net_pnl'] > 0]['net_pnl'].mean() if winning_trades > 0 else 0\n",
    "        avg_loss = trades_df[trades_df['net_pnl'] < 0]['net_pnl'].mean() if losing_trades > 0 else 0\n",
    "        profit_factor = abs(avg_win * winning_trades / (avg_loss * losing_trades)) if losing_trades > 0 else float('inf')\n",
    "        \n",
    "        daily_returns = daily_pnl_series.values\n",
    "        sharpe_ratio = np.mean(daily_returns) / np.std(daily_returns) if np.std(daily_returns) != 0 else 0\n",
    "        \n",
    "        cumulative_pnl = trades_df['net_pnl'].cumsum()\n",
    "        running_max = cumulative_pnl.expanding().max()\n",
    "        drawdown = cumulative_pnl - running_max\n",
    "        max_drawdown = drawdown.min()\n",
    "        \n",
    "        return {\n",
    "            'trades_df': trades_df,\n",
    "            'daily_pnl': daily_pnl_series,\n",
    "            'summary': {\n",
    "                'total_trades': total_trades,\n",
    "                'long_trades': len(trades_df[trades_df['type'] == 'LONG']),\n",
    "                'short_trades': len(trades_df[trades_df['type'] == 'SHORT']),\n",
    "                'winning_trades': winning_trades,\n",
    "                'losing_trades': losing_trades,\n",
    "                'win_rate': win_rate,\n",
    "                'total_pnl': total_pnl,\n",
    "                'gross_pnl': gross_pnl,\n",
    "                'total_transaction_costs': total_transaction_costs,\n",
    "                'avg_pnl_per_trade': total_pnl / total_trades if total_trades > 0 else 0,\n",
    "                'profitable_days': profitable_days,\n",
    "                'losing_days': losing_days,\n",
    "                'total_trading_days': len(daily_pnl_series),\n",
    "                'daily_win_rate': profitable_days / len(daily_pnl_series) * 100 if len(daily_pnl_series) > 0 else 0,\n",
    "                'max_daily_gain': daily_pnl_series.max(),\n",
    "                'max_daily_loss': daily_pnl_series.min(),\n",
    "                'avg_daily_pnl': daily_pnl_series.mean(),\n",
    "                'daily_pnl_std': daily_pnl_series.std(),\n",
    "                'avg_winning_trade': avg_win,\n",
    "                'avg_losing_trade': avg_loss,\n",
    "                'profit_factor': profit_factor,\n",
    "                'sharpe_ratio': sharpe_ratio,\n",
    "                'max_drawdown': max_drawdown,\n",
    "                'transaction_cost_ratio': total_transaction_costs / gross_pnl * 100 if gross_pnl > 0 else 0\n",
    "            }\n",
    "        }\n",
    "\n",
    "print(\"✅ Strategy class defined successfully!\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "execute-strategy",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Execute Trading Strategy\n",
    "if 'combined_data' in locals() and not combined_data.empty:\n",
    "    strategy = SP500IntradayMomentumStrategy(\n",
    "        entry_bps=ENTRY_THRESHOLD_BPS,\n",
    "        stop_loss_bps=STOP_LOSS_BPS,\n",
    "        profit_target_bps=PROFIT_TARGET_BPS,\n",
    "        transaction_cost=TRANSACTION_COST,\n",
    "        tick_value=TICK_VALUE\n",
    "    )\n",
    "    \n",
    "    print(\"\\n\" + \"=\"*60)\n",
    "    print(\"🚀 S&P 500 INTRADAY MOMENTUM STRATEGY BACKTEST\")\n",
    "    print(\"=\"*60)\n",
    "    print(f\"Period: {combined_data['date'].min().strftime('%Y-%m-%d')} to {combined_data['date'].max().strftime('%Y-%m-%d')}\")\n",
    "    print(f\"Entry Threshold: {ENTRY_THRESHOLD_BPS} bps\")\n",
    "    print(f\"Stop Loss: {STOP_LOSS_BPS} bps\")\n",
    "    print(f\"Profit Target: {PROFIT_TARGET_BPS} bps\")\n",
    "    print(f\"Transaction Cost: ${TRANSACTION_COST}\")\n",
    "    print(\"=\"*60)\n",
    "    \n",
    "    results = strategy.backtest(combined_data)\n",
    "    \n",
    "    if results:\n",
    "        summary = results['summary']\n",
    "        print(f\"\\n🎯 SUMMARY RESULTS\")\n",
    "        print(f\"{'='*50}\")\n",
    "        print(f\"Total Trades: {summary['total_trades']:,}\")\n",
    "        print(f\"  - Long Trades: {summary['long_trades']:,}\")\n",
    "        print(f\"  - Short Trades: {summary['short_trades']:,}\")\n",
    "        print(f\"Win Rate: {summary['win_rate']:.2f}%\")\n",
    "        print(f\"Total Net P&L: ${summary['total_pnl']:,.2f}\")\n",
    "        print(f\"Gross P&L: ${summary['gross_pnl']:,.2f}\")\n",
    "        print(f\"Transaction Costs: ${summary['total_transaction_costs']:,.2f}\")\n",
    "        print(f\"Average P&L per Trade: ${summary['avg_pnl_per_trade']:.2f}\")\n",
    "        print(f\"Daily Win Rate: {summary['daily_win_rate']:.1f}%\")\n",
    "        print(f\"Sharpe Ratio: {summary['sharpe_ratio']:.3f}\")\n",
    "        print(f\"Max Drawdown: ${summary['max_drawdown']:,.2f}\")\n",
    "        print(f\"Transaction Cost Ratio: {summary['transaction_cost_ratio']:.2f}%\")\n",
    "    else:\n",
    "        print(\"❌ No trades generated. Check strategy parameters.\")\n",
    "else:\n",
    "    print(\"❌ No data available. Load data first.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "performance-reporting",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Performance Reporting and Visualization\n",
    "def generate_performance_report(results):\n",
    "    if not results:\n",
    "        print(\"No results to report\")\n",
    "        return\n",
    "    \n",
    "    summary = results['summary']\n",
    "    trades_df = results['trades_df']\n",
    "    daily_pnl = results['daily_pnl']\n",
    "    \n",
    "    # Create comprehensive visualizations\n",
    "    fig = plt.figure(figsize=(20, 15))\n",
    "    \n",
    "    # 1. Cumulative P&L\n",
    "    ax1 = plt.subplot(3, 3, 1)\n",
    "    cumulative_pnl = trades_df['net_pnl'].cumsum()\n",
    "    ax1.plot(cumulative_pnl.index, cumulative_pnl.values, linewidth=2, color='green